### PR TITLE
feat/vui

### PR DESCRIPTION
**Pull request by JarbasAl**
add intents to enable/disable ggwave, starts disabled

we dont want devices always processing ggwave tones, this should only happen when enabled by user

add a 15 min timeout, so not keep enabled forever

add handlers for uninstall operations

### CODE REVIEW

**Review by mikejgray — COMMENTED** [review]
Why are we doing a VUI in the plugin here, vs separate elsewhere? I'm not necessarily opposed but would like to understand the reasoning behind one vs the other

**Comment by JarbasAl** [comment]
If the plugin os replaceable with another one that reacts to same.bus messages, then the vui should be a companion skill, if the vui is exclusive to the plugin then it doesn't need to be in it's own repo, it could, but is there ever a reason to do so instead of shipping it with the mandatory code? Avoid the situation of having the skill and no plugin at all

**Comment by JarbasAl** [comment]
Also note on this case the skill is not exposed as a skill plugin, it's loaded as part of the plugin itself, the plugin bundles it's voice interface. We already do this with OCP and Persona, and same happening in CommonIOT kinda, so it's not a new pattern

**Comment by mikejgray** [comment]
> Also note on this case the skill is not exposed as a skill plugin, it's loaded as part of the plugin itself, the plugin bundles it's voice interface. We already do this with OCP and Persona, and same happening in CommonIOT kinda, so it's not a new pattern

It's definitely not a new pattern, no, but I wanted to understand what the reasoning was behind choosing one vs. another. It's more clear now. Thanks for clarifying!

**Pull request merged**
